### ISSUE TITLE
how to install by hand?

### ISSUE THREAD

**Issue by ykla** [qodrorid/wppg#1]
I can't open WordPress admin web. I want to install it by hand. What should I do. Thanks.

**Comment by ykla** [comment]
I am using PG11, php73 and WordPress 5.0.1.

**Comment by agusnurwanto** [comment]
Install and active postgress db in Settings > WPPG > change database to Postgressql

**Comment by ykla** [comment]
This is my first install WordPress, I need to config something like database username password and then I will finish it. So I can't into WordPress and can't into Settings.
My website: 
http://www.freebsdxs.cn

**Comment by thomastthai** [comment]
@ykla do you still need help with this? It's been over a year but I happened to see this today.
